### ISSUE TITLE
TweakBox isn't supported

### ISSUE THREAD

**Issue by lululombard** [lululombard/CertRemainTime#18]
Unfortunately, I don't have a jailbroken device anymore.
Maybe @FaZeIlLuMiNaTi can check that ?
Thanks.

**Comment by FaZeIlLuMiNaTi** [comment]
I'm already taking a look at adding compatibility with enterprise provisioning profiles :)

**Comment by ultra360** [comment]
Here’s the zip file requested by GlorifiedIlLuMiNaTi.
I’m on iPhone X 11.3.1, Electra 1.0.3, multipath tcp exploit installed from Tweakbox.
Cheers!
[ProvisioningProfiles.zip](https://github.com/lululombard/CertRemainTime/files/2180373/ProvisioningProfiles.zip)

**Comment by FaZeIlLuMiNaTi** [comment]
@lululombard I believe this should work. I've added checks for XC- (as well as the pre-existing checks for CY-) in SignedCert.m - this worked for me using Electra from https://ignition.fun/. I don't believe checking Xcode signed provisioning profiles will be an issue, as there is a whitelist of applications that will prevent a personal project appearing in Cert Time. Perhaps in the future I'll work on determining what version of Electra is being used (Electra (11-11.1.2) or Electra1131 (VFS or MP)). Depending on the outcome of the test below, I'll push my local source and a production deb ready for BigBoss.

@ultra360 Here's a version I've quickly thrown together, let me know if it works for you. Unzip with Filza and install the deb.
[fr.lululombard.certremaintime_2.3.5-1+debug_iphoneos-arm.deb.zip](https://github.com/lululombard/CertRemainTime/files/2180425/fr.lululombard.certremaintime_2.3.5-1.debug_iphoneos-arm.deb.zip)

**Comment by lululombard** [comment]
@FaZeIlLuMiNaTi thank you very much :)

**Comment by ultra360** [comment]
@FaZeIlLuMiNaTi Thank you, but I'm still getting "State: No certificate compatible"

**Comment by FaZeIlLuMiNaTi** [comment]
@ultra360 Having just downloaded the TweakBox version of Electra, I can verify that this does not solve the issue. I will continue to investigate this further when I have some spare time. In the meantime, if you want to see the remaining time of Electra signed with an enterprise certificate, you can use the version of Electra from https://ignition.fun/.

**Comment by ultra360** [comment]
Not a problem at all, I just wanted to let you know about the issue.
Ignition is not letting me download Electra right now, but I have Ext3nder Installer installed (I needed  it for the vfs version at first) and it does what I need.

**Comment by FaZeIlLuMiNaTi** [comment]
I did some investigation and I’ve found the cause of the issue.

Apps signed with Xcode have an appID or “XC- AppNameHere” and apps signed with Cydia Impactor have an appID of “CY- AppNameHere”. Cert Time will cut the XC-/CY- from the appID and present it within the app. When I compiled that test deb, I added a clause for Xcode signed apps, this made ignition’s Electra work.

However, TweakBox have signed their Electra differently (I don’t know much about signing), the appID is “dingshengapp” - this seems to be in line with whoever’s enterprise account was used to sign the app (in this case, it was “DingshengcaifuInvestment Management (Beijing) Co.”). The problem with this kind of signing is that the actual name of the tool isn’t included in the appID, and the signing identifier (XC-/CY-) does not exists. This makes it hard to identify the certificate, as there is no generic string available to search by.

In this deb, I’ve added a clause for an appID of “dingshengapp”, meaning Electra signed with this certificate will be detected by Cert Time. This isn’t an ideal solution, because if the tool is resigned using a different enterprise certificate, Cert Time will need an update to detect the new certificate. I’m busy for most/if not all of today, so I won’t be able to look at a better solution for a while, but here’s my current workaround.
[fr.lululombard.certremaintime_2.3.5-8+debug_iphoneos-arm.zip](https://github.com/lululombard/CertRemainTime/files/2187848/fr.lululombard.certremaintime_2.3.5-8%2Bdebug_iphoneos-arm.zip)

Let me know how it goes.

**Comment by ultra360** [comment]
It works now. Hopefully they won’t resign Electra with a different certificate ;)
Glad I could help!

![e3de04f1-c244-4bd2-818b-7f283bd768ee](https://user-images.githubusercontent.com/15080127/42634723-4913d484-85e4-11e8-8b4c-ffba787f3891.png)

**Comment by FaZeIlLuMiNaTi** [comment]
Brilliant, I’m glad I could help. Sometime in the (hopefully near) future, I’ll think of a more realistic solution to this and an update will be pushed via BigBoss.

@lululombard I’ll leave this issue open until a proper fix is pushed.

**Comment by lululombard** [comment]
That’s great ! Let me know when you have a new version to release :)

**Comment by lululombard** [comment]
Update pushed to BigBoss, should be live in 48hrs max 😄
